export default  [
  { name: 'Indian Ocean Territories', iso_n3: -99 },
  { name: 'Siachen Glacier', iso_n3: -99 },
  { name: 'Kosovo', iso_n3: -99 },
  { name: 'Somaliland', iso_n3: -99 },
  { name: 'Northern Cyprus', iso_n3: -99 },
  { name: 'Ashmore and Cartier Islands', iso_n3: 36 },
  { name: 'Aruba', iso_n3: 533 },
  { name: 'Afghanistan', iso_n3: 4 },
  { name: 'Angola', iso_n3: 24 },
  { name: 'Anguilla', iso_n3: 660 },
  { name: 'Aland Islands', iso_n3: 248 },
  { name: 'Albania', iso_n3: 8 },
  { name: 'Andorra', iso_n3: 20 },
  { name: 'United Arab Emirates', iso_n3: 784 },
  { name: 'Argentina', iso_n3: 32 },
  { name: 'Armenia', iso_n3: 51 },
  { name: 'American Samoa', iso_n3: 16 },
  { name: 'Antarctica', iso_n3: 10 },
  { name: 'French Southern Territories', iso_n3: 260 },
  { name: 'Antigua and Barbuda', iso_n3: 28 },
  { name: 'Australia', iso_n3: 36 },
  { name: 'Austria', iso_n3: 40 },
  { name: 'Azerbaijan', iso_n3: 31 },
  { name: 'Burundi', iso_n3: 108 },
  { name: 'Belgium', iso_n3: 56 },
  { name: 'Benin', iso_n3: 204 },
  { name: 'Burkina Faso', iso_n3: 854 },
  { name: 'Bangladesh', iso_n3: 50 },
  { name: 'Bulgaria', iso_n3: 100 },
  { name: 'Bahrain', iso_n3: 48 },
  { name: 'Bahamas', iso_n3: 44 },
  { name: 'Bosnia and Herzegovina', iso_n3: 70 },
  { name: 'Saint-Barthélemy', iso_n3: 652 },
  { name: 'Belarus', iso_n3: 112 },
  { name: 'Belize', iso_n3: 84 },
  { name: 'Bermuda', iso_n3: 60 },
  { name: 'Bolivia, Plurinational State of', iso_n3: 68 },
  { name: 'Brazil', iso_n3: 76 },
  { name: 'Barbados', iso_n3: 52 },
  { name: 'Brunei Darussalam', iso_n3: 96 },
  { name: 'Bhutan', iso_n3: 64 },
  { name: 'Botswana', iso_n3: 72 },
  { name: 'Central African Republic', iso_n3: 140 },
  { name: 'Canada', iso_n3: 124 },
  { name: 'Switzerland', iso_n3: 756 },
  { name: 'Chile', iso_n3: 152 },
  { name: 'China', iso_n3: 156 },
  { name: "Cote d'Ivoire", iso_n3: 384 },
  { name: 'Cameroon', iso_n3: 120 },
  { name: 'Congo, the Democratic Republic of the', iso_n3: 180 },
  { name: 'Congo', iso_n3: 178 },
  { name: 'Cook Islands', iso_n3: 184 },
  { name: 'Colombia', iso_n3: 170 },
  { name: 'Comoros', iso_n3: 174 },
  { name: 'Cape Verde', iso_n3: 132 },
  { name: 'Costa Rica', iso_n3: 188 },
  { name: 'Cuba', iso_n3: 192 },
  { name: 'Curaçao', iso_n3: 531 },
  { name: 'Cayman Islands', iso_n3: 136 },
  { name: 'Cyprus', iso_n3: 196 },
  { name: 'Czech Republic', iso_n3: 203 },
  { name: 'Germany', iso_n3: 276 },
  { name: 'Djibouti', iso_n3: 262 },
  { name: 'Dominica', iso_n3: 212 },
  { name: 'Denmark', iso_n3: 208 },
  { name: 'Dominican Republic', iso_n3: 214 },
  { name: 'Algeria', iso_n3: 12 },
  { name: 'Ecuador', iso_n3: 218 },
  { name: 'Egypt', iso_n3: 818 },
  { name: 'Eritrea', iso_n3: 232 },
  { name: 'Western Sahara', iso_n3: 732 },
  { name: 'Spain', iso_n3: 724 },
  { name: 'Estonia', iso_n3: 233 },
  { name: 'Ethiopia', iso_n3: 231 },
  { name: 'Finland', iso_n3: 246 },
  { name: 'Fiji', iso_n3: 242 },
  { name: 'Falkland Islands (Malvinas)', iso_n3: 238 },
  { name: 'France', iso_n3: 250 },
  { name: 'Faeroe Islands', iso_n3: 234 },
  { name: 'Federated States of Micronesia', iso_n3: 583 },
  { name: 'Gabon', iso_n3: 266 },
  { name: 'United Kingdom', iso_n3: 826 },
  { name: 'Georgia', iso_n3: 268 },
  { name: 'Guernsey', iso_n3: 831 },
  { name: 'Ghana', iso_n3: 288 },
  { name: 'Guinea', iso_n3: 324 },
  { name: 'Gambia', iso_n3: 270 },
  { name: 'Guinea-Bissau', iso_n3: 624 },
  { name: 'Equatorial Guinea', iso_n3: 226 },
  { name: 'Greece', iso_n3: 300 },
  { name: 'Grenada', iso_n3: 308 },
  { name: 'Greenland', iso_n3: 304 },
  { name: 'Guatemala', iso_n3: 320 },
  { name: 'Guam', iso_n3: 316 },
  { name: 'Guyana', iso_n3: 328 },
  { name: 'Hong Kong', iso_n3: 344 },
  { name: 'Heard I. and McDonald Islands', iso_n3: 334 },
  { name: 'Honduras', iso_n3: 340 },
  { name: 'Croatia', iso_n3: 191 },
  { name: 'Haiti', iso_n3: 332 },
  { name: 'Hungary', iso_n3: 348 },
  { name: 'Indonesia', iso_n3: 360 },
  { name: 'Isle of Man', iso_n3: 833 },
  { name: 'India', iso_n3: 356 },
  { name: 'British Indian Ocean Territory', iso_n3: 86 },
  { name: 'Ireland', iso_n3: 372 },
  { name: 'Iran, Islamic Republic of', iso_n3: 364 },
  { name: 'Iraq', iso_n3: 368 },
  { name: 'Iceland', iso_n3: 352 },
  { name: 'Israel', iso_n3: 376 },
  { name: 'Italy', iso_n3: 380 },
  { name: 'Jamaica', iso_n3: 388 },
  { name: 'Jersey', iso_n3: 832 },
  { name: 'Jordan', iso_n3: 400 },
  { name: 'Japan', iso_n3: 392 },
  { name: 'Kazakhstan', iso_n3: 398 },
  { name: 'Kenya', iso_n3: 404 },
  { name: 'Kyrgyzstan', iso_n3: 417 },
  { name: 'Cambodia', iso_n3: 116 },
  { name: 'Kiribati', iso_n3: 296 },
  { name: 'Saint Kitts and Nevis', iso_n3: 659 },
  { name: 'Korea, Republic of', iso_n3: 410 },
  { name: 'Kuwait', iso_n3: 414 },
  { name: "Lao People's Democratic Republic", iso_n3: 418 },
  { name: 'Lebanon', iso_n3: 422 },
  { name: 'Liberia', iso_n3: 430 },
  { name: 'Libya', iso_n3: 434 },
  { name: 'Saint Lucia', iso_n3: 662 },
  { name: 'Liechtenstein', iso_n3: 438 },
  { name: 'Sri Lanka', iso_n3: 144 },
  { name: 'Lesotho', iso_n3: 426 },
  { name: 'Lithuania', iso_n3: 440 },
  { name: 'Luxembourg', iso_n3: 442 },
  { name: 'Latvia', iso_n3: 428 },
  { name: 'Macao', iso_n3: 446 },
  { name: 'Saint-Martin', iso_n3: 663 },
  { name: 'Morocco', iso_n3: 504 },
  { name: 'Monaco', iso_n3: 492 },
  { name: 'Moldova, Republic of', iso_n3: 498 },
  { name: 'Madagascar', iso_n3: 450 },
  { name: 'Maldives', iso_n3: 462 },
  { name: 'Mexico', iso_n3: 484 },
  { name: 'Marshall Islands', iso_n3: 584 },
  { name: 'Macedonia, the former Yugoslav Republic of', iso_n3: 807 },
  { name: 'Mali', iso_n3: 466 },
  { name: 'Malta', iso_n3: 470 },
  { name: 'Myanmar', iso_n3: 104 },
  { name: 'Montenegro', iso_n3: 499 },
  { name: 'Mongolia', iso_n3: 496 },
  { name: 'Northern Mariana Islands', iso_n3: 580 },
  { name: 'Mozambique', iso_n3: 508 },
  { name: 'Mauritania', iso_n3: 478 },
  { name: 'Montserrat', iso_n3: 500 },
  { name: 'Mauritius', iso_n3: 480 },
  { name: 'Malawi', iso_n3: 454 },
  { name: 'Malaysia', iso_n3: 458 },
  { name: 'Namibia', iso_n3: 516 },
  { name: 'New Caledonia', iso_n3: 540 },
  { name: 'Niger', iso_n3: 562 },
  { name: 'Norfolk Island', iso_n3: 574 },
  { name: 'Nigeria', iso_n3: 566 },
  { name: 'Nicaragua', iso_n3: 558 },
  { name: 'Niue', iso_n3: 570 },
  { name: 'Netherlands', iso_n3: 528 },
  { name: 'Norway', iso_n3: 578 },
  { name: 'Nepal', iso_n3: 524 },
  { name: 'Nauru', iso_n3: 520 },
  { name: 'New Zealand', iso_n3: 554 },
  { name: 'Oman', iso_n3: 512 },
  { name: 'Pakistan', iso_n3: 586 },
  { name: 'Panama', iso_n3: 591 },
  { name: 'Pitcairn Islands', iso_n3: 612 },
  { name: 'Peru', iso_n3: 604 },
  { name: 'Philippines', iso_n3: 608 },
  { name: 'Palau', iso_n3: 585 },
  { name: 'Papua New Guinea', iso_n3: 598 },
  { name: 'Poland', iso_n3: 616 },
  { name: 'Puerto Rico', iso_n3: 630 },
  { name: "Korea, Democratic People's Republic of", iso_n3: 408 },
  { name: 'Portugal', iso_n3: 620 },
  { name: 'Paraguay', iso_n3: 600 },
  { name: 'Palestinian Territory, Occupied', iso_n3: 275 },
  { name: 'French Polynesia', iso_n3: 258 },
  { name: 'Qatar', iso_n3: 634 },
  { name: 'Romania', iso_n3: 642 },
  { name: 'Russian Federation', iso_n3: 643 },
  { name: 'Rwanda', iso_n3: 646 },
  { name: 'Saudi Arabia', iso_n3: 682 },
  { name: 'Sudan', iso_n3: 729 },
  { name: 'Senegal', iso_n3: 686 },
  { name: 'Singapore', iso_n3: 702 },
  { name: 'South Georgia and South Sandwich Islands', iso_n3: 239 },
  { name: 'Saint Helena', iso_n3: 654 },
  { name: 'Solomon Islands', iso_n3: 90 },
  { name: 'Sierra Leone', iso_n3: 694 },
  { name: 'El Salvador', iso_n3: 222 },
  { name: 'San Marino', iso_n3: 674 },
  { name: 'Somalia', iso_n3: 706 },
  { name: 'Saint Pierre and Miquelon', iso_n3: 666 },
  { name: 'Serbia', iso_n3: 688 },
  { name: 'South Sudan', iso_n3: 728 },
  { name: 'São Tomé and Principe', iso_n3: 678 },
  { name: 'Suriname', iso_n3: 740 },
  { name: 'Slovakia', iso_n3: 703 },
  { name: 'Slovenia', iso_n3: 705 },
  { name: 'Sweden', iso_n3: 752 },
  { name: 'Eswatini', iso_n3: 748 },
  { name: 'Sint Maarten', iso_n3: 534 },
  { name: 'Seychelles', iso_n3: 690 },
  { name: 'Syrian Arab Republic', iso_n3: 760 },
  { name: 'Turks and Caicos Islands', iso_n3: 796 },
  { name: 'Chad', iso_n3: 148 },
  { name: 'Togo', iso_n3: 768 },
  { name: 'Thailand', iso_n3: 764 },
  { name: 'Tajikistan', iso_n3: 762 },
  { name: 'Turkmenistan', iso_n3: 795 },
  { name: 'Timor-Leste', iso_n3: 626 },
  { name: 'Tonga', iso_n3: 776 },
  { name: 'Trinidad and Tobago', iso_n3: 780 },
  { name: 'Tunisia', iso_n3: 788 },
  { name: 'Turkey', iso_n3: 792 },
  { name: 'Taiwan, Province of China', iso_n3: 158 },
  { name: 'Tanzania, United Republic of', iso_n3: 834 },
  { name: 'Uganda', iso_n3: 800 },
  { name: 'Ukraine', iso_n3: 804 },
  { name: 'Uruguay', iso_n3: 858 },
  { name: 'United States', iso_n3: 840 },
  { name: 'Uzbekistan', iso_n3: 860 },
  { name: 'Vatican', iso_n3: 336 },
  { name: 'Saint Vincent and the Grenadines', iso_n3: 670 },
  { name: 'Venezuela, Bolivarian Republic of', iso_n3: 862 },
  { name: 'British Virgin Islands', iso_n3: 92 },
  { name: 'United States Virgin Islands', iso_n3: 850 },
  { name: 'Viet Nam', iso_n3: 704 },
  { name: 'Vanuatu', iso_n3: 548 },
  { name: 'Wallis and Futuna Islands', iso_n3: 876 },
  { name: 'Samoa', iso_n3: 882 },
  { name: 'Yemen', iso_n3: 887 },
  { name: 'South Africa', iso_n3: 710 },
  { name: 'Zambia', iso_n3: 894 },
  { name: 'Zimbab', iso_n3: 716 },
];